# Generated by Django 5.0.1 on 2024-02-03 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField()),
                ('unique_uuid', models.CharField(max_length=100)),
                ('origin_unique_id', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('creation_timestamp', models.DateTimeField()),
                ('main_text', models.TextField()),
                ('token_count', models.IntegerField()),
                ('char_count', models.IntegerField()),
                ('tag_count', models.IntegerField()),
                ('origin_platform', models.CharField(max_length=100)),
                ('origin_url', models.CharField(max_length=1000)),
                ('like_count', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_apis.author')),
            ],
        ),
        migrations.CreateModel(
            name='MediaUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('media_type', models.CharField(max_length=1000)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content_apis.content')),
            ],
        ),
    ]
