# Generated by Django 5.0.1 on 2024-02-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='char_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='creation_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='main_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='origin_platform',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='origin_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='origin_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='tag_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='token_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='unique_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='unique_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mediaurls',
            name='media_type',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mediaurls',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
