# Generated by Django 5.0.1 on 2024-02-03 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_apis', '0002_alter_author_author_id_alter_author_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='content_apis.author'),
        ),
    ]
