# Generated by Django 5.0.1 on 2024-02-03 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_apis', '0003_alter_content_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='content_apis.author'),
        ),
        migrations.AlterField(
            model_name='mediaurls',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_urls', to='content_apis.content'),
        ),
    ]
