# Generated by Django 5.0.1 on 2024-02-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_apis', '0006_alter_userinfo_user_id_alter_videourl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videourl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_urls', to='content_apis.userinfo'),
        ),
    ]
